### ISSUE TITLE
vite+gulp

### ISSUE THREAD

**Issue by LeonsCd** [magicLaLa/Kitty-plus#2]
hello,
最近准备弄一个vue2组件库，看到了你这个文档，感觉还不错，有一些问题想问，不知道能否得到回复
1.你说的不建议用于项目中开发，仅用于学习，是表示vite+vue2坑很多么 
2.我看你是有一个        
  async () => buildStyle(),   
  async () => buildComponent()  
看了一下style是用的gulp打包的，其他的是vite打包的，这个是有什么说法吗

**Comment by magicLaLa** [comment]
> hello, 最近准备弄一个vue2组件库，看到了你这个文档，感觉还不错，有一些问题想问，不知道能否得到回复 1.你说的不建议用于项目中开发，仅用于学习，是表示vite+vue2坑很多么 2.我看你是有一个 async () => buildStyle(), async () => buildComponent() 看了一下style是用的gulp打包的，其他的是vite打包的，这个是有什么说法吗

1. 可以用了，我已经在项目中使用了。
2. 用来单独处理样式的，先把 less 编译成 css，保持当前目录结构，然后在 处理 vue 模板时 把 当前 script 标签内部引入的 .less 文件变成 .css 文件，但是目录结构保持不变，应该是这样，我是根据 参考那个修改的。
